
version: v1.0
name: ceph-s3-tests-build
jobs:
  - job: Package for ubuntu/20.04
    steps:

      - gitClone:
          branch: '{{ .git.branch }}'
          commit: '{{ .git.hash }}'
          depth: "false"
          directory: '{{ .cds.workspace }}'
          privateKey: proj-ssh-openio
          url: '{{ .git.url }}'

      - name: Clone external-packages
        script:
          - eval $(worker key install --env-git proj-ssh-openio)
          - git clone {{ .cds.proj.STASH_URL }}/openio/external-packages.git /external-packages

      - name: Check known failures files
        script: |+
          #!/bin/bash
          RED='\033[0;31m'
          NC='\033[0m' # No Color
          for infra_id in $(sed -n -E 's/.*"infra_id": "([[:digit:]]+)".*/\1/p' .cds/ceph-s3-tests.yml)
          do
            if [ ! -f "known-failures/${infra_id}.yaml" ]
            then
                echo -e "Missing file ${RED}known-failures/${infra_id}.yaml${NC}"
                exit 1
            fi
          done

      - name: Build package and upload
        script: |+
          #!/bin/bash
          exec &> >(tee -a package-20.04.log)
          trap 'worker upload package-20.04.log' EXIT
          cat $0
          #set -x
          set -e
          # dev or prod release
          . .cds/versions
          export VERSION=1.0-focal
          PACKAGE=ceph-s3-tests
          export REPO_SUBREPO=main
          export REPO_LIMIT=0
          if [[ "{{ .git.tag }}" =~  ^[0-9]+\. ]]; then
            PACKAGE=${PACKAGE}-{{ .git.tag }}
          else
            PACKAGE=${PACKAGE}-$(date +%Y%m%d).git{{ .git.hash.short }}
          fi
          export PACKAGE=${PACKAGE}-ovh${CDS_VERSION}
          export REPO_URL="https://{{ .cds.proj.drive_mirrors_objectstorage_openio_user }}:{{ .cds.proj.drive_mirrors_objectstorage_openio_password }}@{{ .cds.proj.drive_mirrors_hostname }}"
          make -f /external-packages/ubuntu/focal/Makefile.common install-apt-repo
          make -f /external-packages/ubuntu/focal/Makefile.common deb_changelog
          make -f /external-packages/ubuntu/focal/Makefile.common
          make -f /external-packages/ubuntu/focal/Makefile.common upload_to_artifacts
          make -f /external-packages/ubuntu/focal/Makefile.common upload_to_repo
    requirements:
      - model: openio-debbuild-20.04
