version: v1.0
name: root
jobs:
  - job: Check configuration
    requirements:
      - binary: yamllint
    steps:
      - name: Checkout application
        checkout: '{{ .cds.workspace }}'
      - name: Check YAML files
        script:
          - yamllint .cds/ known-failures/
